name: Deploy FastAPI to Azure Web App

env:
  AZURE_WEBAPP_NAME: ${{ secrets.AZURE_WEBAPP_NAME }}  # App name from GitHub Secrets
  PYTHON_VERSION: '3.10'  # Set to the Python version compatible with your app

on:
  push:
    branches:
      - beta-version

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: 'Checkout Code'
        uses: actions/checkout@v4

      # Step 2: Set up Python environment
      - name: 'Set up Python'
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      # Step 3: Create and activate a virtual environment
      - name: 'Create and Activate Virtual Environment'
        run: |
          python -m venv venv
          source venv/bin/activate

      # Step 4: Set up pip caching
      - name: 'Cache pip dependencies'
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      # Step 5: Install dependencies
      - name: 'Install Dependencies'
        run: |
          venv/bin/pip install -r requirements.txt

      # Step 6: Upload artifact for deployment
      - name: 'Upload Artifact for Deployment'
        uses: actions/upload-artifact@v4
        with:
          name: python-app
          path: |
            .
            !venv/

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      # Step 1: Download artifact from build job
      - name: 'Download Artifact'
        uses: actions/download-artifact@v4
        with:
          name: python-app
          path: .

      # Step 2: Deploy to Azure Web App
      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}



# name: Deploy FastAPI to Azure Web App

# on:
#   push:
#     branches:
#       - beta-version

# env:
#   AZURE_WEBAPP_PACKAGE_PATH: './'  # Path to your FastAPI app

# jobs:
#   build-and-deploy:
#     runs-on: ubuntu-latest

#     steps:
#       # Step 1: Checkout the code
#       - name: 'Checkout Code'
#         uses: actions/checkout@v2

#       # Step 2: Set up Python environment
#       - name: 'Set up Python'
#         uses: actions/setup-python@v2
#         with:
#           python-version: '3.10'  # Use the Python version compatible with your app

#       # Step 3: Install dependencies
#       - name: 'Install Dependencies'
#         run: |
#           python -m pip install --upgrade pip
#           pip install -r requirements.txt

#       # Step 4: Run Tests (optional but recommended)
#       # Add your test scripts if available; otherwise, you can skip this step.
#       - name: 'Run Tests'
#         run: |
#           # Assuming you have tests, you can run them here
#           # Example: pytest tests/
#           echo "No tests defined"

#       # Step 5: Deploy to Azure Web App
#       - name: 'Deploy to Azure Web App'
#         uses: azure/webapps-deploy@v2
#         with:
#           app-name: ${{ secrets.AZURE_WEBAPP_NAME }}
#           publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
#           package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
