name: Deploy FastAPI to Azure Web App

on:
  push:
    branches:
      - beta-version

env:
  AZURE_WEBAPP_PACKAGE_PATH: './'  # Path to your FastAPI app

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: 'Checkout Code'
        uses: actions/checkout@v2

      # Step 2: Set up Python environment
      - name: 'Set up Python'
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'  # Use the Python version compatible with your app

      # Step 3: Install dependencies
      - name: 'Install Dependencies'
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Step 4: Run Tests (optional but recommended)
      # Add your test scripts if available; otherwise, you can skip this step.
      - name: 'Run Tests'
        run: |
          # Assuming you have tests, you can run them here
          # Example: pytest tests/
          echo "No tests defined"

      # Step 5: Deploy to Azure Web App
      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ secrets.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
